### ISSUE TITLE
Running without sudo? / Characteristics don't appear

### ISSUE THREAD

**Issue by hut** [ukBaz/BLE_GATT#7] opened 2021-04-27 03:15 UTC
Hi & thank you for this library.

~~The README says that it should be run without sudo. I can connect to a device, but whenever I try reading a characteristic, I get this error:~~

```gi.repository.GLib.Error: g-io-error-quark: GDBus.Error:org.bluez.Error.NotPermitted: Read not permitted (36)```

~~On a Linux Machine with Ubuntu 20.04.2 LTS.~~

~~I already tried:~~

- ~~Setting capabilities on /usr/bin/python as well as ../python/dist-packages/gi/_gi.cpython-38-x86_64-linux-gnu.so [as described here](https://github.com/pybluez/pybluez/issues/184)~~
- ~~In the DBUS config, I added all permissions that root has to everyone in the bluetooth group (of which my user is a part of) [as described here](https://unix.stackexchange.com/questions/348441/how-to-allow-non-root-systemd-service-to-use-dbus-for-ble-operation)~~

~~No luck. How do you do this?~~

**Comment by hut** [comment] 2021-04-27 05:13
Actually, this has nothing to do with root. The characteristic literally has no Read permissions, so nevermind that.

My actual problem is that most of the characteristics simply don't show up in central.chrcs. Not even my services appear in `self.mngr.GetManagedObjects()`.I only see the "Generic Attribute/Service Changed" characteristic (the one I was trying to read originally, and which seems to be some maintenance thing that the ArduinoBLE library adds automatically.) Other programs like gatttool or the "BLE Tool" android app show all of the services and characteristics.

Do you perhaps know of any reason why characteristics wouldn't show up?

P.S. my device is a simple Arduino BLE 33 Sense running https://github.com/arduino-libraries/ArduinoBLE/blob/master/examples/Peripheral/BatteryMonitor/BatteryMonitor.ino

**Comment by hut** [comment] 2021-04-27 05:39
The library https://github.com/getsenic/gatt-python doesn't show the services/characteristics either, so probably it's not a bug in your lib, and I just messed something up. Feel free to close.

**Comment by ukBaz** [comment] 2021-04-27 05:54
When running your script have separate terminals open with the following running to get more debug information:

- bluetootctl
- journalctl -f -u bluetooth
- sudo busctl monitor org.bluez
- sudo btmon

You might also want to check that your device is giving the correct information with a generic Bluetooth Low Energy scanning and exploration tool. The two I point people towards are:
- [nRF Connect](https://www.nordicsemi.com/Software-and-tools/Development-Tools/nRF-Connect-for-mobile)
- If you have a recent version of the Chrome browser then use the URL:   chrome://bluetooth-internals/#devices

Sounds like the issue is more generic than an issue with Bluezero so I'll close this issue, but if there is an issue with this library then please re-open

**Closed as completed by ukBaz** 2021-04-27 05:54 UTC

**Comment by hut** [comment] 2021-04-29 16:48
For posterity, I think the characteristics didn't show up because I used reserved UUIDs. Generating random UUIDs solved the problem.

Thanks again @ukBaz for the elegant library and the helpful pointers for debugging BLE. :)
